apiVersion: v1
kind: ConfigMap
metadata:
  name: hta-config
  namespace: hta-calibration
data:
  NODE_ENV: "development"
  NEXTAUTH_URL: "https://dev.htacalibration.com"
  GCS_CERTIFICATES_BUCKET: "hta-calibration-prod-certificates-dev"
  GCS_SIGNATURES_BUCKET: "hta-calibration-prod-signatures-dev"
  GCS_UPLOADS_BUCKET: "hta-calibration-prod-uploads-dev"
