apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hta-web
  namespace: hta-calibration
  labels:
    app.kubernetes.io/name: hta-web
    app.kubernetes.io/part-of: hta-calibration
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hta-web
