apiVersion: v1
kind: ServiceAccount
metadata:
  name: hta-app
  namespace: hta-calibration
  labels:
    app.kubernetes.io/name: hta-calibration
    app.kubernetes.io/part-of: hta-calibration
  annotations:
    iam.gke.io/gcp-service-account: hta-app-dev@hta-calibration-prod.iam.gserviceaccount.com
