apiVersion: v1
kind: Service
metadata:
  name: hta-web
  namespace: hta-calibration
  labels:
    app.kubernetes.io/name: hta-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: hta-calibration
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: hta-web
