apiVersion: v1
kind: ConfigMap
metadata:
  name: hta-config
  namespace: hta-calibration
data:
  NODE_ENV: "staging"
  NEXTAUTH_URL: "https://staging.hta-calibration.com"
  AUTH_URL: "https://staging.hta-calibration.com"
  GCS_CERTIFICATES_BUCKET: "hta-calibration-prod-certificates-staging"
  GCS_SIGNATURES_BUCKET: "hta-calibration-prod-signatures-staging"
  GCS_UPLOADS_BUCKET: "hta-calibration-prod-uploads-staging"
