apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: hta-calibration-staging

namespace: hta-calibration

resources:
  - ../../base

labels:
  - pairs:
      environment: staging
    includeSelectors: false

patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
  - path: hpa-patch.yaml
  - path: serviceaccount-patch.yaml
  - path: external-secrets-patch.yaml
  - path: ingress-patch.yaml
